AFFILIATION_STATE_MAPPING = {
    "Amazonas Department": "Amazonas",
    "Antioquia Department": "Antioquia",
    "Atlántico Department": "Atlántico",
    "Bogota D.C.": "Bogotá",
    "Bogotá, D. C.": "Bogotá",
    "Bogotá, D.C.": "Bogotá",
    "Caldas Department": "Caldas",
    "Casanare Department": "Casanare",
    "Cauca Department": "Cauca",
    "Cesar Department": "Cesar",
    "Cundinamarca Department": "Cundinamarca",
    "Huila Department": "Huila",
    "La Guajira Department": "La Guajira",
    "Magdalena Department": "Magdalena",
    "Meta Department": "Meta",
    "Norte de Santander Department": "Norte de Santander",
    "Quindío Department": "Quindío",
    "Risaralda Department": "Risaralda",
    "San Andres y Providencia": "San Andrés",
    "Santander Department": "Santander",
    "Sucre Department": "Sucre",
    "Tolima Department": "Tolima",
    "Valle del Cauca Department": "Valle del Cauca",
    "Archipiélago de San Andrés, Providencia y Santa Catalina": "San Andrés",
}

AFFILIATION_CITY_MAPPING = {
    "Bogotá, D.C.": "Bogotá",
    "Cartagena de Indias": "Cartagena",
    "Santiago de Cali": "Cali",
    "Santiago de Tolú": "Tolú",
}
