version: '3.8'
services:
  dev:
    container_name: quyca-dev
    network_mode: host
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: colav/quyca-dev:dev
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["poetry", "run", "python", "./quyca/app.py"]

  prod:
    container_name: quyca-prod
    network_mode: host
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: colav/quyca-prod:latest
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [ "poetry", "run", "python", "./quyca/app.py" ]

  local:
    container_name: quyca-local
    network_mode: host
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    image: colav/quyca-local:local
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [ "poetry", "run", "python", "./quyca/app.py" ]