version: '3.9'

services:
    impactu-database-service:
        build:
            context: ..
            dockerfile: docker/Dockerfile.test
        working_dir: /usr/src/app/app
        command: python -m pytest
        volumes:
            - ../:/usr/src/app/
        env_file:
            - ../.env
        networks:
            - impactu
        restart: on-failure

networks:
    impactu:
        external: True