version: '3.9'

services:
    impactu-database-service:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: python app/app.py
        volumes:
            - ../:/usr/src/app/
        ports:
            - "8002:8010"
            - "10001:10001"
        env_file:
            - ../.env
        networks:
            - impactu
        restart: on-failure

    mongo:
        image: mongo:6.0.11
        restart: always
        ports:
        - '27017:27017'
        env_file:
        - ../.env
        networks:
        - impactu
        volumes:
        - ../db/mongo-data:/data/db
            

networks:
    impactu:
        external: True